//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Shop
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сотрудник.
    /// </summary>
    // *** Start programmer edit section *** (Employee CustomAttributes)

    // *** End programmer edit section *** (Employee CustomAttributes)
    [AutoAltered()]
    [Caption("Сотрудник")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("EmployeeE", new string[] {
            "Number as \'Табельный номер\'",
            "LastName as \'Фамилия\'",
            "FirstName as \'Имя\'",
            "MiddleName as \'Отчество\'",
            "Phone as \'Телефон\'",
            "Email as \'Электронная почта\'"})]
    [View("EmployeeL", new string[] {
            "Number as \'Табельный номер\'",
            "LastName as \'Фамилия\'",
            "FirstName as \'Имя\'",
            "MiddleName as \'Отчество\'",
            "Phone as \'Телефон\'",
            "Email as \'Электронная почта\'"})]
    public class Employee : ICSSoft.STORMNET.DataObject
    {
        
        private int fNumber = 1;
        
        private string fLastName;
        
        private string fFirstName;
        
        private string fMiddleName;
        
        private string fPhone;
        
        private string fEmail;
        
        // *** Start programmer edit section *** (Employee CustomMembers)

        // *** End programmer edit section *** (Employee CustomMembers)

        
        /// <summary>
        /// Number.
        /// </summary>
        // *** Start programmer edit section *** (Employee.Number CustomAttributes)

        // *** End programmer edit section *** (Employee.Number CustomAttributes)
        [DisableInsertProperty(true)]
        [NotNull()]
        public virtual int Number
        {
            get
            {
                // *** Start programmer edit section *** (Employee.Number Get start)

                // *** End programmer edit section *** (Employee.Number Get start)
                int result = this.fNumber;
                // *** Start programmer edit section *** (Employee.Number Get end)

                // *** End programmer edit section *** (Employee.Number Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Employee.Number Set start)

                // *** End programmer edit section *** (Employee.Number Set start)
                this.fNumber = value;
                // *** Start programmer edit section *** (Employee.Number Set end)

                // *** End programmer edit section *** (Employee.Number Set end)
            }
        }
        
        /// <summary>
        /// LastName.
        /// </summary>
        // *** Start programmer edit section *** (Employee.LastName CustomAttributes)

        // *** End programmer edit section *** (Employee.LastName CustomAttributes)
        [StrLen(255)]
        public virtual string LastName
        {
            get
            {
                // *** Start programmer edit section *** (Employee.LastName Get start)

                // *** End programmer edit section *** (Employee.LastName Get start)
                string result = this.fLastName;
                // *** Start programmer edit section *** (Employee.LastName Get end)

                // *** End programmer edit section *** (Employee.LastName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Employee.LastName Set start)

                // *** End programmer edit section *** (Employee.LastName Set start)
                this.fLastName = value;
                // *** Start programmer edit section *** (Employee.LastName Set end)

                // *** End programmer edit section *** (Employee.LastName Set end)
            }
        }
        
        /// <summary>
        /// FirstName.
        /// </summary>
        // *** Start programmer edit section *** (Employee.FirstName CustomAttributes)

        // *** End programmer edit section *** (Employee.FirstName CustomAttributes)
        [StrLen(255)]
        public virtual string FirstName
        {
            get
            {
                // *** Start programmer edit section *** (Employee.FirstName Get start)

                // *** End programmer edit section *** (Employee.FirstName Get start)
                string result = this.fFirstName;
                // *** Start programmer edit section *** (Employee.FirstName Get end)

                // *** End programmer edit section *** (Employee.FirstName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Employee.FirstName Set start)

                // *** End programmer edit section *** (Employee.FirstName Set start)
                this.fFirstName = value;
                // *** Start programmer edit section *** (Employee.FirstName Set end)

                // *** End programmer edit section *** (Employee.FirstName Set end)
            }
        }
        
        /// <summary>
        /// MiddleName.
        /// </summary>
        // *** Start programmer edit section *** (Employee.MiddleName CustomAttributes)

        // *** End programmer edit section *** (Employee.MiddleName CustomAttributes)
        [StrLen(255)]
        public virtual string MiddleName
        {
            get
            {
                // *** Start programmer edit section *** (Employee.MiddleName Get start)

                // *** End programmer edit section *** (Employee.MiddleName Get start)
                string result = this.fMiddleName;
                // *** Start programmer edit section *** (Employee.MiddleName Get end)

                // *** End programmer edit section *** (Employee.MiddleName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Employee.MiddleName Set start)

                // *** End programmer edit section *** (Employee.MiddleName Set start)
                this.fMiddleName = value;
                // *** Start programmer edit section *** (Employee.MiddleName Set end)

                // *** End programmer edit section *** (Employee.MiddleName Set end)
            }
        }
        
        /// <summary>
        /// Phone.
        /// </summary>
        // *** Start programmer edit section *** (Employee.Phone CustomAttributes)

        // *** End programmer edit section *** (Employee.Phone CustomAttributes)
        [StrLen(255)]
        public virtual string Phone
        {
            get
            {
                // *** Start programmer edit section *** (Employee.Phone Get start)

                // *** End programmer edit section *** (Employee.Phone Get start)
                string result = this.fPhone;
                // *** Start programmer edit section *** (Employee.Phone Get end)

                // *** End programmer edit section *** (Employee.Phone Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Employee.Phone Set start)

                // *** End programmer edit section *** (Employee.Phone Set start)
                this.fPhone = value;
                // *** Start programmer edit section *** (Employee.Phone Set end)

                // *** End programmer edit section *** (Employee.Phone Set end)
            }
        }
        
        /// <summary>
        /// Email.
        /// </summary>
        // *** Start programmer edit section *** (Employee.Email CustomAttributes)

        // *** End programmer edit section *** (Employee.Email CustomAttributes)
        [StrLen(255)]
        public virtual string Email
        {
            get
            {
                // *** Start programmer edit section *** (Employee.Email Get start)

                // *** End programmer edit section *** (Employee.Email Get start)
                string result = this.fEmail;
                // *** Start programmer edit section *** (Employee.Email Get end)

                // *** End programmer edit section *** (Employee.Email Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Employee.Email Set start)

                // *** End programmer edit section *** (Employee.Email Set start)
                this.fEmail = value;
                // *** Start programmer edit section *** (Employee.Email Set end)

                // *** End programmer edit section *** (Employee.Email Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "EmployeeE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View EmployeeE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("EmployeeE", typeof(IIS.Shop.Employee));
                }
            }
            
            /// <summary>
            /// "EmployeeL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View EmployeeL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("EmployeeL", typeof(IIS.Shop.Employee));
                }
            }
        }
    }
}
