//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Shop
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Запись в накладной.
    /// </summary>
    // *** Start programmer edit section *** (InvoiceString CustomAttributes)

    // *** End programmer edit section *** (InvoiceString CustomAttributes)
    [AutoAltered()]
    [Caption("Запись в накладной")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("InvoiceStringE", new string[] {
            "Product as \'Товар\'",
            "Amount as \'Количество\'",
            "Weight as \'Вес\'",
            "Price as \'Цена\'",
            "TotalSum as \'Сумма по позиции\'"})]
    [MasterViewDefineAttribute("InvoiceStringE", "Product", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    public class InvoiceString : ICSSoft.STORMNET.DataObject
    {
        
        private int fAmount;
        
        private double fWeight;
        
        private double fPrice;
        
        private double fTotalSum;
        
        private IIS.Shop.Product fProduct;
        
        private IIS.Shop.Invoice fInvoice;
        
        // *** Start programmer edit section *** (InvoiceString CustomMembers)

        // *** End programmer edit section *** (InvoiceString CustomMembers)

        
        /// <summary>
        /// Amount.
        /// </summary>
        // *** Start programmer edit section *** (InvoiceString.Amount CustomAttributes)

        // *** End programmer edit section *** (InvoiceString.Amount CustomAttributes)
        public virtual int Amount
        {
            get
            {
                // *** Start programmer edit section *** (InvoiceString.Amount Get start)

                // *** End programmer edit section *** (InvoiceString.Amount Get start)
                int result = this.fAmount;
                // *** Start programmer edit section *** (InvoiceString.Amount Get end)

                // *** End programmer edit section *** (InvoiceString.Amount Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (InvoiceString.Amount Set start)

                // *** End programmer edit section *** (InvoiceString.Amount Set start)
                this.fAmount = value;
                // *** Start programmer edit section *** (InvoiceString.Amount Set end)

                // *** End programmer edit section *** (InvoiceString.Amount Set end)
            }
        }
        
        /// <summary>
        /// Weight.
        /// </summary>
        // *** Start programmer edit section *** (InvoiceString.Weight CustomAttributes)

        // *** End programmer edit section *** (InvoiceString.Weight CustomAttributes)
        public virtual double Weight
        {
            get
            {
                // *** Start programmer edit section *** (InvoiceString.Weight Get start)

                // *** End programmer edit section *** (InvoiceString.Weight Get start)
                double result = this.fWeight;
                // *** Start programmer edit section *** (InvoiceString.Weight Get end)

                // *** End programmer edit section *** (InvoiceString.Weight Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (InvoiceString.Weight Set start)

                // *** End programmer edit section *** (InvoiceString.Weight Set start)
                this.fWeight = value;
                // *** Start programmer edit section *** (InvoiceString.Weight Set end)

                // *** End programmer edit section *** (InvoiceString.Weight Set end)
            }
        }
        
        /// <summary>
        /// Price.
        /// </summary>
        // *** Start programmer edit section *** (InvoiceString.Price CustomAttributes)

        // *** End programmer edit section *** (InvoiceString.Price CustomAttributes)
        public virtual double Price
        {
            get
            {
                // *** Start programmer edit section *** (InvoiceString.Price Get start)

                // *** End programmer edit section *** (InvoiceString.Price Get start)
                double result = this.fPrice;
                // *** Start programmer edit section *** (InvoiceString.Price Get end)

                // *** End programmer edit section *** (InvoiceString.Price Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (InvoiceString.Price Set start)

                // *** End programmer edit section *** (InvoiceString.Price Set start)
                this.fPrice = value;
                // *** Start programmer edit section *** (InvoiceString.Price Set end)

                // *** End programmer edit section *** (InvoiceString.Price Set end)
            }
        }
        
        /// <summary>
        /// TotalSum.
        /// </summary>
        // *** Start programmer edit section *** (InvoiceString.TotalSum CustomAttributes)

        // *** End programmer edit section *** (InvoiceString.TotalSum CustomAttributes)
        public virtual double TotalSum
        {
            get
            {
                // *** Start programmer edit section *** (InvoiceString.TotalSum Get start)

                // *** End programmer edit section *** (InvoiceString.TotalSum Get start)
                double result = this.fTotalSum;
                // *** Start programmer edit section *** (InvoiceString.TotalSum Get end)

                // *** End programmer edit section *** (InvoiceString.TotalSum Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (InvoiceString.TotalSum Set start)

                // *** End programmer edit section *** (InvoiceString.TotalSum Set start)
                this.fTotalSum = value;
                // *** Start programmer edit section *** (InvoiceString.TotalSum Set end)

                // *** End programmer edit section *** (InvoiceString.TotalSum Set end)
            }
        }
        
        /// <summary>
        /// Запись в накладной.
        /// </summary>
        // *** Start programmer edit section *** (InvoiceString.Product CustomAttributes)

        // *** End programmer edit section *** (InvoiceString.Product CustomAttributes)
        [PropertyStorage(new string[] {
                "Товар"})]
        public virtual IIS.Shop.Product Product
        {
            get
            {
                // *** Start programmer edit section *** (InvoiceString.Product Get start)

                // *** End programmer edit section *** (InvoiceString.Product Get start)
                IIS.Shop.Product result = this.fProduct;
                // *** Start programmer edit section *** (InvoiceString.Product Get end)

                // *** End programmer edit section *** (InvoiceString.Product Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (InvoiceString.Product Set start)

                // *** End programmer edit section *** (InvoiceString.Product Set start)
                this.fProduct = value;
                // *** Start programmer edit section *** (InvoiceString.Product Set end)

                // *** End programmer edit section *** (InvoiceString.Product Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Shop.Invoice.
        /// </summary>
        // *** Start programmer edit section *** (InvoiceString.Invoice CustomAttributes)

        // *** End programmer edit section *** (InvoiceString.Invoice CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Накладная"})]
        public virtual IIS.Shop.Invoice Invoice
        {
            get
            {
                // *** Start programmer edit section *** (InvoiceString.Invoice Get start)

                // *** End programmer edit section *** (InvoiceString.Invoice Get start)
                IIS.Shop.Invoice result = this.fInvoice;
                // *** Start programmer edit section *** (InvoiceString.Invoice Get end)

                // *** End programmer edit section *** (InvoiceString.Invoice Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (InvoiceString.Invoice Set start)

                // *** End programmer edit section *** (InvoiceString.Invoice Set start)
                this.fInvoice = value;
                // *** Start programmer edit section *** (InvoiceString.Invoice Set end)

                // *** End programmer edit section *** (InvoiceString.Invoice Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "InvoiceStringE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View InvoiceStringE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("InvoiceStringE", typeof(IIS.Shop.InvoiceString));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of InvoiceString.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfInvoiceString CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfInvoiceString CustomAttributes)
    public class DetailArrayOfInvoiceString : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Shop.DetailArrayOfInvoiceString members)

        // *** End programmer edit section *** (IIS.Shop.DetailArrayOfInvoiceString members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type InvoiceString by index.
        /// </summary>
        /// <summary>
        /// Adds object with type InvoiceString.
        /// </summary>
        public DetailArrayOfInvoiceString(IIS.Shop.Invoice fInvoice) : 
                base(typeof(InvoiceString), ((ICSSoft.STORMNET.DataObject)(fInvoice)))
        {
        }
        
        public IIS.Shop.InvoiceString this[int index]
        {
            get
            {
                return ((IIS.Shop.InvoiceString)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Shop.InvoiceString dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
