//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Shop
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Строка заказа.
    /// </summary>
    // *** Start programmer edit section *** (OrderString CustomAttributes)

    // *** End programmer edit section *** (OrderString CustomAttributes)
    [AutoAltered()]
    [Caption("Строка заказа")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("OrderStringE", new string[] {
            "Product as \'Товар\'",
            "Amount as \'Количество\'",
            "PriceWTaxes as \'Цена с налогом\'",
            "TotalSum as \'Сумма по позиции\'"})]
    [MasterViewDefineAttribute("OrderStringE", "Product", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    public class OrderString : ICSSoft.STORMNET.DataObject
    {
        
        private int fAmount;
        
        private double fPriceWTaxes;
        
        private double fTotalSum;
        
        private IIS.Shop.Product fProduct;
        
        private IIS.Shop.Order fOrder;
        
        // *** Start programmer edit section *** (OrderString CustomMembers)

        // *** End programmer edit section *** (OrderString CustomMembers)

        
        /// <summary>
        /// Amount.
        /// </summary>
        // *** Start programmer edit section *** (OrderString.Amount CustomAttributes)

        // *** End programmer edit section *** (OrderString.Amount CustomAttributes)
        public virtual int Amount
        {
            get
            {
                // *** Start programmer edit section *** (OrderString.Amount Get start)

                // *** End programmer edit section *** (OrderString.Amount Get start)
                int result = this.fAmount;
                // *** Start programmer edit section *** (OrderString.Amount Get end)

                // *** End programmer edit section *** (OrderString.Amount Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (OrderString.Amount Set start)

                // *** End programmer edit section *** (OrderString.Amount Set start)
                this.fAmount = value;
                // *** Start programmer edit section *** (OrderString.Amount Set end)

                // *** End programmer edit section *** (OrderString.Amount Set end)
            }
        }
        
        /// <summary>
        /// PriceWTaxes.
        /// </summary>
        // *** Start programmer edit section *** (OrderString.PriceWTaxes CustomAttributes)

        // *** End programmer edit section *** (OrderString.PriceWTaxes CustomAttributes)
        public virtual double PriceWTaxes
        {
            get
            {
                // *** Start programmer edit section *** (OrderString.PriceWTaxes Get start)

                // *** End programmer edit section *** (OrderString.PriceWTaxes Get start)
                double result = this.fPriceWTaxes;
                // *** Start programmer edit section *** (OrderString.PriceWTaxes Get end)

                // *** End programmer edit section *** (OrderString.PriceWTaxes Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (OrderString.PriceWTaxes Set start)

                // *** End programmer edit section *** (OrderString.PriceWTaxes Set start)
                this.fPriceWTaxes = value;
                // *** Start programmer edit section *** (OrderString.PriceWTaxes Set end)

                // *** End programmer edit section *** (OrderString.PriceWTaxes Set end)
            }
        }
        
        /// <summary>
        /// TotalSum.
        /// </summary>
        // *** Start programmer edit section *** (OrderString.TotalSum CustomAttributes)

        // *** End programmer edit section *** (OrderString.TotalSum CustomAttributes)
        public virtual double TotalSum
        {
            get
            {
                // *** Start programmer edit section *** (OrderString.TotalSum Get start)

                // *** End programmer edit section *** (OrderString.TotalSum Get start)
                double result = this.fTotalSum;
                // *** Start programmer edit section *** (OrderString.TotalSum Get end)

                // *** End programmer edit section *** (OrderString.TotalSum Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (OrderString.TotalSum Set start)

                // *** End programmer edit section *** (OrderString.TotalSum Set start)
                this.fTotalSum = value;
                // *** Start programmer edit section *** (OrderString.TotalSum Set end)

                // *** End programmer edit section *** (OrderString.TotalSum Set end)
            }
        }
        
        /// <summary>
        /// Строка заказа.
        /// </summary>
        // *** Start programmer edit section *** (OrderString.Product CustomAttributes)

        // *** End programmer edit section *** (OrderString.Product CustomAttributes)
        [PropertyStorage(new string[] {
                "Товар"})]
        public virtual IIS.Shop.Product Product
        {
            get
            {
                // *** Start programmer edit section *** (OrderString.Product Get start)

                // *** End programmer edit section *** (OrderString.Product Get start)
                IIS.Shop.Product result = this.fProduct;
                // *** Start programmer edit section *** (OrderString.Product Get end)

                // *** End programmer edit section *** (OrderString.Product Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (OrderString.Product Set start)

                // *** End programmer edit section *** (OrderString.Product Set start)
                this.fProduct = value;
                // *** Start programmer edit section *** (OrderString.Product Set end)

                // *** End programmer edit section *** (OrderString.Product Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Shop.Order.
        /// </summary>
        // *** Start programmer edit section *** (OrderString.Order CustomAttributes)

        // *** End programmer edit section *** (OrderString.Order CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Заказ"})]
        public virtual IIS.Shop.Order Order
        {
            get
            {
                // *** Start programmer edit section *** (OrderString.Order Get start)

                // *** End programmer edit section *** (OrderString.Order Get start)
                IIS.Shop.Order result = this.fOrder;
                // *** Start programmer edit section *** (OrderString.Order Get end)

                // *** End programmer edit section *** (OrderString.Order Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (OrderString.Order Set start)

                // *** End programmer edit section *** (OrderString.Order Set start)
                this.fOrder = value;
                // *** Start programmer edit section *** (OrderString.Order Set end)

                // *** End programmer edit section *** (OrderString.Order Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "OrderStringE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View OrderStringE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("OrderStringE", typeof(IIS.Shop.OrderString));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of OrderString.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfOrderString CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfOrderString CustomAttributes)
    public class DetailArrayOfOrderString : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Shop.DetailArrayOfOrderString members)

        // *** End programmer edit section *** (IIS.Shop.DetailArrayOfOrderString members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type OrderString by index.
        /// </summary>
        /// <summary>
        /// Adds object with type OrderString.
        /// </summary>
        public DetailArrayOfOrderString(IIS.Shop.Order fOrder) : 
                base(typeof(OrderString), ((ICSSoft.STORMNET.DataObject)(fOrder)))
        {
        }
        
        public IIS.Shop.OrderString this[int index]
        {
            get
            {
                return ((IIS.Shop.OrderString)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Shop.OrderString dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
